### ISSUE TITLE
[FYI] Experimentally available from ArchLinux User Repository (AUR)

### ISSUE THREAD

**Issue by kseistrup** [idanpa/calcpy#4]
[ This issue is informational only. No action is necessary on your part, and you may close it at your discretion. ]

I am experimentally packaging calcpy for AUR under the package name `python-calcpy-git`. It packages the latest commit here from Microsoft GitHub and installs it along with the README and the LICENSE.

+ https://aur.archlinux.org/packages/python-calcpy-git

The package can be conveniently installed using an [AUR helper](https://wiki.archlinux.org/title/AUR_helpers), e.g.:

```sh
» yay -S python-calcpy-git
```

Cheers.

**Comment by idanpa** [comment]
Thank you for the update!
Please let me know if you have any issues.
