### ISSUE TITLE
how to calculate percentage easily？

### ISSUE THREAD

**Issue by jackywu** [idanpa/calcpy#5]
hi, it's a magic project, thanks for your good job.
I have a small question. how to calculate what percentage the price rise from A USD to B USD ?
in normal way `(B-A)/A * 100`, I hope we have a more concise way.

**Comment by idanpa** [comment]
Hi @jackywu! Thanks for writing this issue.

You can define functions and use them, they would persist across sessions.
``` python
In [1]: def p(A,B):
   ...:     return (B-A)*100/A
   ...: 
In [2]: p(100,120)
Out[2]: 20.0
```

If this is not what you are looking for, please let me know what you think.
